# Generated by Django 4.0.5 on 2022-06-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('course_hours', models.IntegerField()),
                ('tp_hourse', models.IntegerField()),
                ('td_hours', models.IntegerField()),
                ('section', models.CharField(max_length=128)),
                ('year', models.CharField(max_length=128)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='registrations', to='management.course')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='registrations', to='accounts.doctor')),
            ],
        ),
    ]
