# Generated by Django 4.0.5 on 2022-06-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    def set_my_defaults(apps, schema_editor):
        courses = apps.get_model('management', 'Course')
        for course in courses.objects.all().filter(course_hours__isnull=True):
            course.course_hours = 30
            course.save()

    def reverse_func(apps, schema_editor):
        pass  # code for reverting migration, if any

    dependencies = [
        ('management', '0002_course_course_hours_registration'),
    ]

    operations = [
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.AlterField(
            model_name='course',
            name='course_hours',
            field=models.IntegerField(),
        ),
    ]
