# Generated by Django 4.0.5 on 2022-06-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_tp_hourse_course_tp_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='tp_hourse',
            new_name='tp_hours',
        ),
    ]
