# Generated by Django 4.0.5 on 2022-06-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_registration_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.CharField(blank=True, default='1/1', max_length=128, null=True),
        ),
    ]
