# Generated by Django 4.0.5 on 2022-06-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('father_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('aca_degree', models.CharField(blank=True, max_length=128, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=128, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
